const String kLoremIpsumP1 =
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae tempus quam pellentesque nec. Egestas sed sed risus pretium. Sapien et ligula ullamcorper malesuada. Eget est lorem ipsum dolor. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus in. Porta non pulvinar neque laoreet suspendisse interdum consectetur libero id. Ultrices in iaculis nunc sed augue. Donec et odio pellentesque diam volutpat commodo sed egestas egestas. Iaculis at erat pellentesque adipiscing commodo.';
const String kLoremIpsumP2 =
    'Tincidunt tortor aliquam nulla facilisi cras fermentum. Neque gravida in fermentum et sollicitudin ac orci phasellus egestas. Turpis massa tincidunt dui ut ornare lectus sit amet. Vitae congue eu consequat ac felis donec et odio. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet. Tempus egestas sed sed risus. At in tellus integer feugiat scelerisque. Blandit massa enim nec dui nunc mattis enim ut. Neque ornare aenean euismod elementum nisi quis eleifend quam adipiscing. Aenean pharetra magna ac placerat. Pulvinar etiam non quam lacus suspendisse faucibus interdum posuere. Sit amet consectetur adipiscing elit ut aliquam purus sit amet. Duis ut diam quam nulla porttitor massa id neque. Ultricies mi eget mauris pharetra et ultrices neque. Egestas quis ipsum suspendisse ultrices gravida dictum fusce ut. Sagittis nisl rhoncus mattis rhoncus urna. Adipiscing diam donec adipiscing tristique risus nec. Sit amet commodo nulla facilisi. Integer enim neque volutpat ac tincidunt. Est ullamcorper eget nulla facilisi etiam.';
const String kLoremIpsumP3 =
    'Auctor augue mauris augue neque gravida in. Amet nisl purus in mollis. Nisi porta lorem mollis aliquam ut porttitor leo a diam. Cras semper auctor neque vitae tempus quam pellentesque nec nam. Cum sociis natoque penatibus et magnis dis parturient montes nascetur. Purus ut faucibus pulvinar elementum integer enim. Cras semper auctor neque vitae tempus quam. Auctor neque vitae tempus quam pellentesque nec nam aliquam. Tellus mauris a diam maecenas. Pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus. Lorem ipsum dolor sit amet consectetur adipiscing elit ut. Amet dictum sit amet justo donec enim diam vulputate ut. Aliquam faucibus purus in massa tempor nec feugiat. Massa placerat duis ultricies lacus sed turpis.';
const String kLoremIpsumP4 =
    'Lorem sed risus ultricies tristique nulla aliquet enim tortor. Venenatis urna cursus eget nunc scelerisque viverra mauris in aliquam. Purus in massa tempor nec. Lectus vestibulum mattis ullamcorper velit sed ullamcorper. Mi quis hendrerit dolor magna eget. Donec massa sapien faucibus et molestie ac. Vitae sapien pellentesque habitant morbi tristique senectus et. Nibh cras pulvinar mattis nunc sed. Enim eu turpis egestas pretium aenean pharetra magna ac. Sed viverra tellus in hac habitasse. Donec ac odio tempor orci dapibus ultrices in iaculis nunc. Auctor eu augue ut lectus arcu bibendum at varius vel.';
const String kLoremIpsumP5 =
    'Consectetur adipiscing elit pellentesque habitant morbi tristique senectus et. Aliquet nibh praesent tristique magna sit amet purus gravida quis. Auctor neque vitae tempus quam pellentesque nec nam aliquam. Auctor eu augue ut lectus arcu bibendum. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus urna neque. Tincidunt eget nullam non nisi est sit. Vitae tempus quam pellentesque nec nam aliquam sem et tortor. Quis enim lobortis scelerisque fermentum dui faucibus in ornare. Tortor consequat id porta nibh venenatis. Sed tempus urna et pharetra pharetra massa massa. Justo laoreet sit amet cursus sit amet dictum sit amet. Turpis tincidunt id aliquet risus. Augue mauris augue neque gravida in fermentum et sollicitudin. Metus vulputate eu scelerisque felis imperdiet proin fermentum. Nec feugiat in fermentum posuere urna nec tincidunt praesent. Diam quam nulla porttitor massa id neque. Euismod quis viverra nibh cras.';
const String kLoremIpsumP6 =
    'Amet consectetur adipiscing elit duis tristique sollicitudin nibh. Hac habitasse platea dictumst quisque sagittis purus. Feugiat pretium nibh ipsum consequat nisl vel pretium lectus quam. Sit amet massa vitae tortor condimentum lacinia quis vel. Eu scelerisque felis imperdiet proin fermentum. Amet commodo nulla facilisi nullam. Tellus in hac habitasse platea. Leo duis ut diam quam nulla. Sem fringilla ut morbi tincidunt. Faucibus ornare suspendisse sed nisi lacus sed. Non blandit massa enim nec. Nibh nisl condimentum id venenatis a condimentum vitae sapien pellentesque. A pellentesque sit amet porttitor eget.';
const String kLoremIpsumP7 =
    'Blandit cursus risus at ultrices. Sed egestas egestas fringilla phasellus faucibus scelerisque. Eget dolor morbi non arcu risus. Sed risus ultricies tristique nulla aliquet enim tortor. Non arcu risus quis varius quam quisque id diam vel. Condimentum lacinia quis vel eros donec ac odio tempor. Consectetur adipiscing elit pellentesque habitant morbi tristique senectus et netus. Nunc pulvinar sapien et ligula ullamcorper malesuada. Sagittis eu volutpat odio facilisis. Lacinia at quis risus sed vulputate. In hendrerit gravida rutrum quisque. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi. A arcu cursus vitae congue mauris rhoncus aenean vel elit. Adipiscing commodo elit at imperdiet dui accumsan sit amet nulla. Urna nec tincidunt praesent semper feugiat nibh sed.';
const String kLoremIpsumP8 =
    'Ornare suspendisse sed nisi lacus sed viverra tellus. Id volutpat lacus laoreet non curabitur. Tempus iaculis urna id volutpat lacus laoreet non curabitur gravida. Eget magna fermentum iaculis eu non diam phasellus. Fames ac turpis egestas maecenas pharetra. Pharetra et ultrices neque ornare aenean. Aliquam nulla facilisi cras fermentum odio. Risus in hendrerit gravida rutrum quisque non tellus orci ac. Morbi tristique senectus et netus et malesuada fames ac turpis. Rhoncus dolor purus non enim praesent elementum. Dictum fusce ut placerat orci nulla pellentesque. Sagittis orci a scelerisque purus semper. Quis varius quam quisque id diam vel. Quis blandit turpis cursus in hac. Libero volutpat sed cras ornare arcu dui. Orci ac auctor augue mauris augue neque gravida.';
const String kLoremIpsumP9 =
    'Vel orci porta non pulvinar neque laoreet suspendisse. Et sollicitudin ac orci phasellus. Pulvinar etiam non quam lacus suspendisse faucibus interdum posuere lorem. Maecenas accumsan lacus vel facilisis volutpat est velit egestas dui. Pellentesque habitant morbi tristique senectus et. Elementum eu facilisis sed odio morbi quis commodo odio. Sed enim ut sem viverra. Placerat orci nulla pellentesque dignissim enim sit. Placerat vestibulum lectus mauris ultrices eros in cursus. Adipiscing enim eu turpis egestas pretium. Pretium viverra suspendisse potenti nullam ac tortor vitae. Ac turpis egestas sed tempus urna et pharetra pharetra massa. Massa sapien faucibus et molestie ac. Pharetra et ultrices neque ornare. Consequat mauris nunc congue nisi vitae suscipit tellus mauris a. Vulputate dignissim suspendisse in est ante in nibh mauris. Amet dictum sit amet justo donec nim diam vulputate. Leo urna molestie at elementum eu. Sed risus ultricies tristique nulla. Amet purus gravida quis blandit.';
const String kLoremIpsumP10 =
    'Rhoncus urna neque viverra justo nec ultrices dui. Amet tellus cras adipiscing enim eu. Pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Nisi vitae suscipit tellus mauris. Vitae suscipit tellus mauris a diam maecenas sed enim ut. Pharetra diam sit amet nisl. Ultricies mi quis hendrerit dolor. Cursus mattis molestie a iaculis at. A diam maecenas sed enim ut sem viverra. Sagittis id consectetur purus ut faucibus pulvinar elementum. Turpis egestas maecenas pharetra convallis posuere morbi. Fusce id velit ut tortor pretium viverra suspendisse potenti nullam. Donec massa sapien faucibus et molestie ac. In ante metus dictum at tempor commodo ullamcorper a. Arcu bibendum at varius vel pharetra vel. A pellentesque sit amet porttitor eget dolor morbi non. Adipiscing at in tellus integer feugiat scelerisque. Diam maecenas ultricies mi eget.';
const String kLoremIpsumP11 =
    'Enim blandit volutpat maecenas volutpat. Enim lobortis scelerisque fermentum dui faucibus in ornare. Facilisis gravida neque convallis a cras semper. At varius vel pharetra vel turpis nunc eget. Amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus et. Venenatis cras sed felis eget velit. Consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Enim eu turpis egestas pretium. Pharetra pharetra massa massa ultricies mi quis hendrerit dolor. Velit dignissim sodales ut eu sem integer vitae justo. Feugiat vivamus at augue eget.';
const String kLoremIpsumP12 =
    'Lacus sed turpis tincidunt id aliquet risus feugiat in ante. Neque vitae tempus quam pellentesque nec nam. Eget nunc lobortis mattis aliquam faucibus purus in. Diam sit amet nisl suscipit adipiscing bibendum. Id velit ut tortor pretium viverra suspendisse potenti nullam. Ut venenatis tellus in metus vulputate eu scelerisque felis. Aliquam faucibus purus in massa tempor nec feugiat. Enim neque volutpat ac tincidunt. Imperdiet sed euismod nisi porta lorem mollis aliquam. At elementum eu facilisis sed. In mollis nunc sed id semper risus in. Ut tellus elementum sagittis vitae. Amet facilisis magna etiam tempor. Pretium nibh ipsum consequat nisl vel pretium lectus. Massa tincidunt nunc pulvinar sapien et ligula. Facilisi etiam dignissim diam quis enim. Vitae tempus quam pellentesque nec nam aliquam.';

const List<String> kLoremIpsumParagraphs = [
  kLoremIpsumP1,
  kLoremIpsumP2,
  kLoremIpsumP3,
  kLoremIpsumP4,
  kLoremIpsumP5,
  kLoremIpsumP6,
  kLoremIpsumP7,
  kLoremIpsumP8,
  kLoremIpsumP9,
  kLoremIpsumP10,
  kLoremIpsumP11,
  kLoremIpsumP12,
];
